name:  the-ur-quan-masters
title:   The Ur-Quan Masters
version: "0.8.0"
summary:    A port of Star Control II - The Ur-Quan Masters for modern operating systems
description: |
  Star Control II - The Ur-Quan Masters was released in 1992 by Accolade. It is the second and final game in the series created by Fred Ford and Paul Reiche III. The original version was created for PC, but later an alternate version was released for the console 3DO, which allowed for the inclusion of speech and a modernized intro. In a similar fashion to Star Control, the full game is made up of two parts, one being arcade spaceship combat called Melee. The tactical gameplay in Star Control has been replaced by an adventure game, where the player travels through the universe and encounters all sorts of challenges.

grade: stable
icon: the-ur-quan-masters_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  the-ur-quan-masters:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files (x86)/The Ur-Quan Masters/uqm.exe"
      INSTALL_EXE: "$SNAP/uqm-0.8-win32.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

